export const COLORS = {
    PRIMARY: '#FA824C',
    SECONDARY: '#FFEECC',
    BLACK: '#333333',
    GRAY: '#DCDCE6',
    LIGHT_GRAY: '#F5F5F5',
    LIGHTEST_GRAY: '#B8B8BF',
    LIGHT_RED: '#FFCCD8'
}